{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [GET] \"/auth/login\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"exception_object_id":15620,"id":0,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:33:in `call'"},{"exception_object_id":15620,"id":1,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"exception_object_id":15620,"id":2,"trace":"railties (6.1.3.2) lib/rails/rack/logger.rb:37:in `call_app'"},{"exception_object_id":15620,"id":3,"trace":"railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `block in call'"},{"exception_object_id":15620,"id":4,"trace":"activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'"},{"exception_object_id":15620,"id":5,"trace":"activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:37:in `tagged'"},{"exception_object_id":15620,"id":6,"trace":"activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `tagged'"},{"exception_object_id":15620,"id":7,"trace":"railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `call'"},{"exception_object_id":15620,"id":8,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"exception_object_id":15620,"id":9,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'"},{"exception_object_id":15620,"id":10,"trace":"rack (2.2.3) lib/rack/runtime.rb:22:in `call'"},{"exception_object_id":15620,"id":11,"trace":"activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"exception_object_id":15620,"id":12,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"exception_object_id":15620,"id":13,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/static.rb:24:in `call'"},{"exception_object_id":15620,"id":14,"trace":"rack (2.2.3) lib/rack/sendfile.rb:110:in `call'"},{"exception_object_id":15620,"id":15,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'"},{"exception_object_id":15620,"id":16,"trace":"railties (6.1.3.2) lib/rails/engine.rb:539:in `call'"},{"exception_object_id":15620,"id":17,"trace":"puma (5.3.2) lib/puma/configuration.rb:249:in `call'"},{"exception_object_id":15620,"id":18,"trace":"puma (5.3.2) lib/puma/request.rb:77:in `block in handle_request'"},{"exception_object_id":15620,"id":19,"trace":"puma (5.3.2) lib/puma/thread_pool.rb:338:in `with_force_shutdown'"},{"exception_object_id":15620,"id":20,"trace":"puma (5.3.2) lib/puma/request.rb:76:in `handle_request'"},{"exception_object_id":15620,"id":21,"trace":"puma (5.3.2) lib/puma/server.rb:438:in `process_client'"},{"exception_object_id":15620,"id":22,"trace":"puma (5.3.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'"}],"Full Trace":[{"exception_object_id":15620,"id":0,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:33:in `call'"},{"exception_object_id":15620,"id":1,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"exception_object_id":15620,"id":2,"trace":"railties (6.1.3.2) lib/rails/rack/logger.rb:37:in `call_app'"},{"exception_object_id":15620,"id":3,"trace":"railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `block in call'"},{"exception_object_id":15620,"id":4,"trace":"activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'"},{"exception_object_id":15620,"id":5,"trace":"activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:37:in `tagged'"},{"exception_object_id":15620,"id":6,"trace":"activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `tagged'"},{"exception_object_id":15620,"id":7,"trace":"railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `call'"},{"exception_object_id":15620,"id":8,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"exception_object_id":15620,"id":9,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'"},{"exception_object_id":15620,"id":10,"trace":"rack (2.2.3) lib/rack/runtime.rb:22:in `call'"},{"exception_object_id":15620,"id":11,"trace":"activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"exception_object_id":15620,"id":12,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"exception_object_id":15620,"id":13,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/static.rb:24:in `call'"},{"exception_object_id":15620,"id":14,"trace":"rack (2.2.3) lib/rack/sendfile.rb:110:in `call'"},{"exception_object_id":15620,"id":15,"trace":"actionpack (6.1.3.2) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'"},{"exception_object_id":15620,"id":16,"trace":"railties (6.1.3.2) lib/rails/engine.rb:539:in `call'"},{"exception_object_id":15620,"id":17,"trace":"puma (5.3.2) lib/puma/configuration.rb:249:in `call'"},{"exception_object_id":15620,"id":18,"trace":"puma (5.3.2) lib/puma/request.rb:77:in `block in handle_request'"},{"exception_object_id":15620,"id":19,"trace":"puma (5.3.2) lib/puma/thread_pool.rb:338:in `with_force_shutdown'"},{"exception_object_id":15620,"id":20,"trace":"puma (5.3.2) lib/puma/request.rb:76:in `handle_request'"},{"exception_object_id":15620,"id":21,"trace":"puma (5.3.2) lib/puma/server.rb:438:in `process_client'"},{"exception_object_id":15620,"id":22,"trace":"puma (5.3.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'"}]}}